CREATE TABLE IF NOT EXISTS aulas(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    number integer NOT NULL,
    edificio text NOT NULL CHECK (edificio <> '')
);

INSERT INTO aulas (name, number, edificio) VALUES ('Aula',  51, 'Bloque 2'); 